apiVersion: v1
kind: Service
metadata:
  name: opcua-service
  namespace: p1-shopfloor  
spec:
  type: ClusterIP  
  selector:
    app: opcua-server
  ports:
  - protocol: TCP
    port: 4840
    targetPort: 4840